Ppipes
sniffd/FWA pull request #1
Opened 2022-01-27 19:33 UTC by morrkof

Пока вместо страничек signUp и signIn заглушки

2022-01-27 20:28 UTC, sniffd requested changes
Будут вопросы - пиши

2022-01-27 20:28 UTC, sniffd commented on ex00/Cinema/pom.xml
>  <!--    </dependency>-->
Закомментированные зависимости в помнике - зло

2022-01-27 20:28 UTC, sniffd commented on ex00/Cinema/pom.xml
> +      <version>5.3.13</version>
Версии групповых зависимостей, да и в целом лучше всех выносить в переменные, дабы было удобно менять в случае необходимости

2022-01-27 20:28 UTC, sniffd commented on ex00/Cinema/src/main/java/edu/school21/cinema/config/ApplicationConfig.java
> +    public PasswordEncoder encodePassword() {
В данном случае название метода = название бина, поэтому не самый удачный выбор

2022-01-27 20:28 UTC, sniffd commented on ex00/Cinema/src/main/java/edu/school21/cinema/config/ApplicationConfig.java
> +    public UserRepositoryImpl usersRepository() throws SQLException, IOException {
user/users следи за окончаниями, иначе не заметишь, как потонешь в хаосе)))

2022-01-27 20:28 UTC, sniffd commented on ex00/Cinema/src/main/java/edu/school21/cinema/models/User.java
> +public class User {
Довольно частой практикой по кодстайлу является пустая строка после начала класса, дабы код визуально не слипался. Я поддерживаю это

2022-01-27 20:28 UTC, sniffd commented on ex00/Cinema/src/main/java/edu/school21/cinema/repositories/CrudRepository.java
> +public interface CrudRepository<T> {
newline

2022-01-27 20:28 UTC, sniffd commented on ex00/Cinema/src/main/java/edu/school21/cinema/repositories/UserRepository.java
> +public interface UserRepository extends CrudRepository<User> {
newline

2022-01-27 20:28 UTC, sniffd commented on ex00/Cinema/src/main/java/edu/school21/cinema/repositories/UserRepositoryImpl.java
> +
вот здесь же поставила, ну)

2022-01-27 20:28 UTC, sniffd commented on ex00/Cinema/src/main/java/edu/school21/cinema/repositories/UserRepositoryImpl.java
> +    private JdbcTemplate jdbcTemplate;
вроде можно final сделать

2022-01-27 20:28 UTC, sniffd commented on ex00/Cinema/src/main/java/edu/school21/cinema/repositories/UserRepositoryImpl.java
> +    @Qualifier("dataSource")
Qualifier вроде здесь излишний. Autowired прямо перед параметром поставить

2022-01-27 20:28 UTC, sniffd commented on ex00/Cinema/src/main/java/edu/school21/cinema/repositories/UserRepositoryImpl.java
> +        } catch (Exception e) {
Ловить глобальные эксепшны не есть гуд

2022-01-27 20:28 UTC, sniffd commented on ex00/Cinema/src/main/java/edu/school21/cinema/repositories/UserRepositoryImpl.java
> +        } catch (Exception e) {
тоже самое

2022-01-27 20:28 UTC, sniffd commented on ex00/Cinema/src/main/java/edu/school21/cinema/services/UsersService.java
> +    @Qualifier("encodePassword")
про это писал уже

2022-01-27 20:28 UTC, sniffd commented on ex00/Cinema/src/main/java/edu/school21/cinema/services/UsersService.java
> +    @Qualifier("usersRepository")
про это писал уже

2022-01-27 20:28 UTC, sniffd commented on ex00/Cinema/src/main/java/edu/school21/cinema/services/UsersService.java
> +            userRepository.save(new User(null, firstname, lastname, email, phone, passwordEncoder.encode(password)));
Для таких случаев можно создать второй конструктор, чтобы руками не пихать null

2022-01-27 20:28 UTC, sniffd commented on ex00/Cinema/src/main/java/edu/school21/cinema/servlets/SignInServlet.java
> +    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
ну камон, просто get

2022-01-27 20:28 UTC, sniffd commented on ex00/Cinema/src/main/java/edu/school21/cinema/servlets/SignInServlet.java
> +    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
post

2022-01-27 20:28 UTC, sniffd commented on ex00/Cinema/src/main/java/edu/school21/cinema/servlets/SignInServlet.java
> +//    private UsersService usersService;
Комменты если не нужны, то убрать

2022-01-27 20:28 UTC, sniffd commented on ex00/Cinema/src/main/java/edu/school21/cinema/servlets/SignUpServlet.java
> +//    private UsersService usersService;
комменты и нейминг

2022-01-27 20:28 UTC, sniffd commented on ex00/Cinema/src/main/resources/application.properties
> +db.driver.name=org.postgresql.Driver
newline добавь

2022-01-27 20:28 UTC, sniffd commented on ex00/Cinema/src/main/resources/sql/data.sql
> +       ('Draco', 'Malfoy', 'dmalfoy@email.com', '89257654567', 'qwe');
newline добавь

2022-01-27 20:28 UTC, sniffd commented on ex00/Cinema/src/main/webapp/WEB-INF/web.xml
> +<!--    <servlet>-->
эти куски нужны?

2022-01-27 20:28 UTC, sniffd commented on ex00/Cinema/src/main/webapp/index.jsp
> +</html>
newline

2022-01-27 20:28 UTC, sniffd commented on ex00/Cinema/src/main/webapp/jsp/signIn.jsp
> +//        if (request.getAttribute("userName") != null) {
это надо?

2022-01-27 20:28 UTC, sniffd commented on ex00/Cinema/src/main/webapp/jsp/signIn.jsp
> +</html>
newline

2022-01-27 20:28 UTC, sniffd commented on ex00/Cinema/src/main/webapp/jsp/signUp.jsp
> +</html>
newline

2022-01-27 20:28 UTC, sniffd commented on ex00/Cinema/src/main/webapp/jsp/signUp.jsp
> +//        if (request.getAttribute("userName") != null) {
это надо?

2022-01-27 20:28 UTC, sniffd commented on ex00/Cinema/src/main/java/edu/school21/cinema/services/UsersService.java
> +    private UserRepository userRepository;
Вообще спринг рекомендует делать инъекции через конструктор. Там и аннотация необязательна будет

2022-01-29 15:26 UTC, morrkof commented on ex00/Cinema/src/main/java/edu/school21/cinema/repositories/UserRepositoryImpl.java
> +    private JdbcTemplate jdbcTemplate;
Он не бин и создаётся в методе дальше, final тут не получится вроде

2022-01-29 15:27 UTC, morrkof commented on ex00/Cinema/src/main/java/edu/school21/cinema/servlets/SignInServlet.java
> +    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
Это заовверрайденные методы родительского класса HttpServlet

2022-01-29 15:27 UTC, morrkof commented on ex00/Cinema/src/main/java/edu/school21/cinema/servlets/SignInServlet.java
> +    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
Это заовверрайденные методы родительского класса HttpServlet

2022-01-29 16:58 UTC, sniffd commented on ex00/Cinema/src/main/java/edu/school21/cinema/repositories/UserRepositoryImpl.java
> +    private JdbcTemplate jdbcTemplate;
Если сделать инъекцию через конструктор, то должно сработать

2022-01-29 16:59 UTC, sniffd commented on ex00/Cinema/src/main/java/edu/school21/cinema/repositories/UserRepositoryImpl.java
> +    private JdbcTemplate jdbcTemplate;
То есть эту же логику, только внутри конструктора. Так даже логичнее будет

2022-01-29 17:22 UTC, sniffd requested changes
Отлично, пару нюансов осталось

2022-01-29 17:22 UTC, sniffd commented on ex00/Cinema/src/main/java/edu/school21/cinema/services/UserService.java
> +    private UserService(@Autowired UserRepository userRepository, @Autowired PasswordEncoder passwordEncoder) {
Попробуй @Autowired убрать. Должно и без них всё произойти

2022-01-29 17:22 UTC, sniffd commented on ex00/Cinema/src/main/java/edu/school21/cinema/servlets/SignInServlet.java
> +    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
Жесть какая

2022-01-29 17:22 UTC, sniffd commented on ex00/Cinema/src/main/java/edu/school21/cinema/servlets/SignUpServlet.java
> +
Лишняя строка

2022-02-23 19:49 UTC, sniffd approved these changes

2022-02-23 19:49 UTC, merged